reviews:
  in_progress_fortune: false
  auto_review:
    enabled: true
    drafts: false

  review_status: true

  path_filters:
    - '!**/node_modules/**'
    - '!**/.next/**'
    - '!**/dist/**'
    - '!**/build/**'
    - '!**/coverage/**'
    - '!**/*.md'
    - '!**/*.lock'
    - '!**/*.log'
    - '!**/.nx/**'
    - '!**/prisma/migrations/**'
    - '!**/package-lock.json'
